// h34/frontend/src/components/layout/Header.tsx
import { useState, useRef, useEffect } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { useQuery } from 'react-query'
import {
  Bell,
  User,
  LogOut,
  Settings,
  ChevronDown,
  Moon,
  Sun,
} from 'lucide-react'
import { useAuth } from '@/store'
import { alertApi } from '@/services/api'
import { clsx } from 'clsx'

export const Header = () => {
  const navigate = useNavigate()
  const { user, logout } = useAuth()
  const [userMenuOpen, setUserMenuOpen] = useState(false)
  const [isDarkMode, setIsDarkMode] = useState(false)
  const userMenuRef = useRef<HTMLDivElement>(null)

  const { data: unreadCount } = useQuery(
    ['alerts', 'unread-count'],
    async () => {
      const response = await alertApi.getUnreadCount()
      return response.data?.count || 0
    }
  )

  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (userMenuRef.current && !userMenuRef.current.contains(event.target as Node)) {
        setUserMenuOpen(false)
      }
    }

    document.addEventListener('mousedown', handleClickOutside)
    return () => document.removeEventListener('mousedown', handleClickOutside)
  }, [])

  const handleLogout = () => {
    logout()
    navigate('/login')
  }

  const toggleTheme = () => {
    setIsDarkMode(!isDarkMode)
    document.documentElement.classList.toggle('dark')
  }

  return (
    <header className="h-16 bg-white border-b border-gray-200 px-6 flex items-center justify-between sticky top-0 z-30">
      <div className="flex items-center gap-4">
        <h2 className="text-lg font-semibold text-gray-900">
          农业病害风险预警系统
        </h2>
      </div>

      <div className="flex items-center gap-3">
        <button
          onClick={toggleTheme}
          className="p-2.5 text-gray-500 hover:text-gray-700 hover:bg-gray-100 rounded-xl transition-colors"
          title={isDarkMode ? '切换到浅色模式' : '切换到深色模式'}
        >
          {isDarkMode ? <Sun className="w-5 h-5" /> : <Moon className="w-5 h-5" />}
        </button>

        <button
          onClick={() => navigate('/alerts')}
          className="relative p-2.5 text-gray-500 hover:text-gray-700 hover:bg-gray-100 rounded-xl transition-colors"
        >
          <Bell className="w-5 h-5" />
          {unreadCount !== undefined && unreadCount > 0 && (
            <span className="absolute top-1 right-1 w-5 h-5 bg-red-500 text-white text-xs font-medium rounded-full flex items-center justify-center">
              {unreadCount > 99 ? '99+' : unreadCount}
            </span>
          )}
        </button>

        <div className="relative" ref={userMenuRef}>
          <button
            onClick={() => setUserMenuOpen(!userMenuOpen)}
            className="flex items-center gap-3 p-1.5 hover:bg-gray-100 rounded-xl transition-colors"
          >
            <div className="w-9 h-9 bg-gradient-to-br from-green-500 to-green-600 rounded-full flex items-center justify-center">
              <User className="w-5 h-5 text-white" />
            </div>
            <div className="text-left hidden sm:block">
              <p className="text-sm font-medium text-gray-900">
                {user?.full_name || user?.email || '用户'}
              </p>
              <p className="text-xs text-gray-500">{user?.email}</p>
            </div>
            <ChevronDown
              className={clsx(
                'w-4 h-4 text-gray-400 transition-transform hidden sm:block',
                userMenuOpen && 'rotate-180'
              )}
            />
          </button>

          {userMenuOpen && (
            <div className="absolute right-0 mt-2 w-56 bg-white rounded-xl shadow-lg border border-gray-200 py-2 z-50">
              <div className="px-4 py-3 border-b border-gray-100">
                <p className="text-sm font-medium text-gray-900">
                  {user?.full_name || '用户'}
                </p>
                <p className="text-xs text-gray-500 truncate">{user?.email}</p>
              </div>

              <div className="py-1">
                <Link
                  to="/settings"
                  onClick={() => setUserMenuOpen(false)}
                  className="flex items-center gap-3 px-4 py-2.5 text-sm text-gray-700 hover:bg-gray-50 transition-colors"
                >
                  <Settings className="w-4 h-4 text-gray-400" />
                  系统设置
                </Link>
              </div>

              <div className="border-t border-gray-100 pt-1">
                <button
                  onClick={handleLogout}
                  className="flex items-center gap-3 px-4 py-2.5 text-sm text-red-600 hover:bg-red-50 w-full transition-colors"
                >
                  <LogOut className="w-4 h-4" />
                  退出登录
                </button>
              </div>
            </div>
          )}
        </div>
      </div>
    </header>
  )
}

export default Header

// h20/src/components/Header.vue
<script setup lang="ts">
import { ref } from 'vue'
import {
  Bell,
  Moon,
  Sun,
  User,
  LogOut,
  Settings,
  ChevronDown
} from 'lucide-vue-next'
import { useTheme } from '../composables/useTheme'

const { theme, toggleTheme, isDark } = useTheme()

const showNotifications = ref(false)
const showUserMenu = ref(false)

interface Notification {
  id: number
  title: string
  message: string
  type: 'info' | 'warning' | 'error'
  time: string
  read: boolean
}

const notifications = ref<Notification[]>([
  { id: 1, title: '新可疑模式', message: '检测到新的洗钱模式', type: 'warning', time: '5分钟前', read: false },
  { id: 2, title: '任务完成', message: '数据导入任务已完成', type: 'info', time: '1小时前', read: false },
  { id: 3, title: '高风险警报', message: '地址 bc1q... 风险评分达到95', type: 'error', time: '2小时前', read: true }
])

const unreadCount = () => notifications.value.filter(n => !n.read).length

const toggleNotifications = () => {
  showNotifications.value = !showNotifications.value
  showUserMenu.value = false
}

const toggleUserMenu = () => {
  showUserMenu.value = !showUserMenu.value
  showNotifications.value = false
}

const markAsRead = (id: number) => {
  const notification = notifications.value.find(n => n.id === id)
  if (notification) notification.read = true
}

const getNotificationColor = (type: string) => {
  switch (type) {
    case 'warning': return 'bg-amber-500'
    case 'error': return 'bg-red-500'
    default: return 'bg-cyan-500'
  }
}
</script>

<template>
  <header class="h-16 bg-slate-900/80 dark:bg-slate-950/80 backdrop-blur-md border-b border-slate-700/50 px-4 flex items-center justify-between">
    <div class="flex items-center gap-3">
      <div class="w-10 h-10 rounded-lg bg-gradient-to-br from-cyan-500 to-blue-600 flex items-center justify-center">
        <span class="text-white font-bold text-lg">B</span>
      </div>
      <div>
        <h1 class="text-lg font-bold text-white">比特币交易分析系统</h1>
        <p class="text-xs text-slate-400">Transaction Intelligence Platform</p>
      </div>
    </div>

    <div class="flex items-center gap-2">
      <button
        class="relative p-2 rounded-lg text-slate-400 hover:bg-slate-800 hover:text-slate-200 transition-all duration-200"
        @click="toggleTheme"
      >
        <Sun v-if="isDark" class="w-5 h-5" />
        <Moon v-else class="w-5 h-5" />
      </button>

      <div class="relative">
        <button
          class="relative p-2 rounded-lg text-slate-400 hover:bg-slate-800 hover:text-slate-200 transition-all duration-200"
          @click="toggleNotifications"
        >
          <Bell class="w-5 h-5" />
          <span
            v-if="unreadCount() > 0"
            class="absolute -top-1 -right-1 w-5 h-5 bg-red-500 text-white text-xs rounded-full flex items-center justify-center"
          >
            {{ unreadCount() }}
          </span>
        </button>

        <Transition name="dropdown">
          <div
            v-if="showNotifications"
            class="absolute right-0 top-full mt-2 w-80 bg-slate-800 dark:bg-slate-900 rounded-lg border border-slate-700 shadow-xl z-50 overflow-hidden"
          >
            <div class="px-4 py-3 border-b border-slate-700">
              <h3 class="text-sm font-semibold text-white">通知</h3>
            </div>
            <div class="max-h-80 overflow-y-auto">
              <div
                v-for="notification in notifications"
                :key="notification.id"
                class="px-4 py-3 border-b border-slate-700/50 hover:bg-slate-700/30 cursor-pointer transition-colors"
                @click="markAsRead(notification.id)"
              >
                <div class="flex items-start gap-3">
                  <div :class="[getNotificationColor(notification.type), 'w-2 h-2 rounded-full mt-2 flex-shrink-0']"></div>
                  <div class="flex-1 min-w-0">
                    <div class="flex items-center justify-between">
                      <p class="text-sm font-medium text-white" :class="{ 'opacity-60': notification.read }">{{ notification.title }}</p>
                      <span class="text-xs text-slate-500 flex-shrink-0 ml-2">{{ notification.time }}</span>
                    </div>
                    <p class="text-xs text-slate-400 mt-1 truncate">{{ notification.message }}</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </Transition>
      </div>

      <div class="relative">
        <button
          class="flex items-center gap-2 px-3 py-2 rounded-lg hover:bg-slate-800 transition-all duration-200"
          @click="toggleUserMenu"
        >
          <div class="w-8 h-8 rounded-full bg-gradient-to-br from-cyan-500 to-blue-600 flex items-center justify-center">
            <User class="w-4 h-4 text-white" />
          </div>
          <span class="text-sm text-slate-300 hidden sm:block">管理员</span>
          <ChevronDown class="w-4 h-4 text-slate-400" />
        </button>

        <Transition name="dropdown">
          <div
            v-if="showUserMenu"
            class="absolute right-0 top-full mt-2 w-48 bg-slate-800 dark:bg-slate-900 rounded-lg border border-slate-700 shadow-xl z-50 overflow-hidden"
          >
            <button class="w-full px-4 py-2.5 text-left text-sm text-slate-300 hover:bg-slate-700/50 flex items-center gap-2 transition-colors">
              <User class="w-4 h-4" />
              个人资料
            </button>
            <button class="w-full px-4 py-2.5 text-left text-sm text-slate-300 hover:bg-slate-700/50 flex items-center gap-2 transition-colors">
              <Settings class="w-4 h-4" />
              系统设置
            </button>
            <div class="border-t border-slate-700"></div>
            <button class="w-full px-4 py-2.5 text-left text-sm text-red-400 hover:bg-red-500/10 flex items-center gap-2 transition-colors">
              <LogOut class="w-4 h-4" />
              退出登录
            </button>
          </div>
        </Transition>
      </div>
    </div>
  </header>
</template>

<style scoped>
.dropdown-enter-active,
.dropdown-leave-active {
  transition: all 0.2s ease;
}

.dropdown-enter-from,
.dropdown-leave-to {
  opacity: 0;
  transform: translateY(-8px);
}
</style>
