// h20/src/components/Sidebar.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import {
  LayoutDashboard,
  GitBranch,
  MapPin,
  Database,
  ListTodo,
  Layers,
  ChevronLeft,
  ChevronRight,
  Brain,
  Shield,
  FileText
} from 'lucide-vue-next'

interface MenuItem {
  path: string
  label: string
  icon: typeof LayoutDashboard
}

const props = defineProps<{
  collapsed: boolean
}>()

const emit = defineEmits<{
  (e: 'toggle-collapse'): void
}>()

const route = useRoute()
const router = useRouter()

const menuItems: MenuItem[] = [
  { path: '/dashboard', label: '仪表盘', icon: LayoutDashboard },
  { path: '/transactions', label: '交易图', icon: GitBranch },
  { path: '/addresses', label: '地址分析', icon: MapPin },
  { path: '/import', label: '数据导入', icon: Database },
  { path: '/tasks', label: '任务管理', icon: ListTodo },
  { path: '/clustering', label: '聚类分析', icon: Layers },
  { path: '/gnn-analysis', label: 'GNN异常评分', icon: Brain },
  { path: '/privacy-analysis', label: '隐私币分析', icon: Shield },
  { path: '/compliance-report', label: '合规报告', icon: FileText }
]

const isActive = (path: string) => {
  return route.path.startsWith(path)
}

const navigateTo = (path: string) => {
  router.push(path)
}
</script>

<template>
  <aside
    class="h-full bg-slate-900 dark:bg-slate-950 border-r border-slate-700/50 flex flex-col transition-all duration-300 ease-in-out"
    :class="[
      collapsed ? 'w-16' : 'w-64'
    ]"
  >
    <div class="flex-1 py-4 overflow-y-auto">
      <nav class="space-y-1 px-2">
        <div
          v-for="item in menuItems"
          :key="item.path"
          class="flex items-center gap-3 px-3 py-2.5 rounded-lg cursor-pointer transition-all duration-200 group"
          :class="[
            isActive(item.path)
              ? 'bg-gradient-to-r from-cyan-500/20 text-cyan-400 border border-cyan-500/30'
              : 'text-slate-400 hover:bg-slate-800/50 hover:text-slate-200 border border-transparent'
          ]"
          @click="navigateTo(item.path)"
        >
          <component
            :is="item.icon"
            class="w-5 h-5 flex-shrink-0 transition-transform duration-200"
            :class="[isActive(item.path) ? 'text-cyan-400' : 'group-hover:scale-110']"
          />
          <span
            class="text-sm font-medium whitespace-nowrap transition-all duration-200"
            :class="[collapsed ? 'opacity-0 w-0 overflow-hidden' : 'opacity-100']"
          >
            {{ item.label }}
          </span>
        </div>
      </nav>
    </div>

    <div class="p-3 border-t border-slate-700/50">
      <button
        class="w-full flex items-center justify-center p-2 rounded-lg text-slate-400 hover:bg-slate-800/50 hover:text-slate-200 transition-all duration-200"
        @click="emit('toggle-collapse')"
      >
        <ChevronLeft v-if="!collapsed" class="w-5 h-5" />
        <ChevronRight v-else class="w-5 h-5" />
        <span
          v-if="!collapsed" class="ml-2 text-sm">收起</span>
      </button>
    </div>
  </aside>
</template>

// h34/frontend/src/components/layout/Sidebar.tsx
import { NavLink, useLocation } from 'react-router-dom'
import {
  LayoutDashboard,
  Map,
  Bell,
  History,
  Settings,
  ChevronLeft,
  ChevronRight,
  Leaf,
} from 'lucide-react'
import { useUI } from '@/store'
import { clsx } from 'clsx'

const menuItems = [
  { path: '/dashboard', label: '仪表盘', icon: LayoutDashboard },
  { path: '/map', label: '风险地图', icon: Map },
  { path: '/alerts', label: '预警管理', icon: Bell },
  { path: '/history', label: '历史数据', icon: History },
  { path: '/settings', label: '系统设置', icon: Settings },
]

export const Sidebar = () => {
  const location = useLocation()
  const { sidebarOpen, toggleSidebar } = useUI()

  return (
    <aside
      className={clsx(
        'fixed left-0 top-0 z-40 h-screen bg-white border-r border-gray-200 transition-all duration-300 flex flex-col',
        sidebarOpen ? 'w-64' : 'w-20'
      )}
    >
      <div className="flex items-center justify-between h-16 px-4 border-b border-gray-200">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 bg-gradient-to-br from-green-500 to-green-600 rounded-xl flex items-center justify-center flex-shrink-0">
            <Leaf className="w-6 h-6 text-white" />
          </div>
          {sidebarOpen && (
            <div className="flex flex-col">
              <span className="font-bold text-gray-900 text-lg">农业风险</span>
              <span className="text-xs text-gray-500">预警系统</span>
            </div>
          )}
        </div>
      </div>

      <nav className="flex-1 p-4 space-y-1 overflow-y-auto">
        {menuItems.map((item) => {
          const Icon = item.icon
          const isActive = location.pathname === item.path
          return (
            <NavLink
              key={item.path}
              to={item.path}
              className={clsx(
                'flex items-center gap-3 px-3 py-3 rounded-xl transition-all duration-200 group',
                isActive
                  ? 'bg-green-50 text-green-600 font-medium'
                  : 'text-gray-600 hover:bg-gray-50 hover:text-gray-900'
              )}
            >
              <Icon
                className={clsx(
                  'w-5 h-5 flex-shrink-0 transition-colors',
                  isActive ? 'text-green-600' : 'text-gray-400 group-hover:text-gray-600'
                )}
              />
              {sidebarOpen && <span className="whitespace-nowrap">{item.label}</span>}
              {!sidebarOpen && (
                <div className="absolute left-20 px-2 py-1 bg-gray-900 text-white text-sm rounded-md opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none whitespace-nowrap z-50">
                  {item.label}
                </div>
              )}
            </NavLink>
          )
        })}
      </nav>

      <div className="p-4 border-t border-gray-200">
        <button
          onClick={toggleSidebar}
          className="w-full flex items-center justify-center gap-2 px-3 py-2.5 text-gray-500 hover:bg-gray-100 rounded-xl transition-colors"
        >
          {sidebarOpen ? (
            <>
              <ChevronLeft className="w-5 h-5" />
              <span>收起菜单</span>
            </>
          ) : (
            <ChevronRight className="w-5 h-5" />
          )}
        </button>
      </div>
    </aside>
  )
}

export default Sidebar
